### ISSUE TITLE
create empty file 

### ISSUE THREAD

**Issue by Pratiktarade** [ericschernoff/HTMLDoc#1]
Hi  Team please check bellow    code 
#######################################
my $htmll = new HTML::HTMLDoc(); 

$htmll->set_page_size('letter'); # set page size
$htmll->set_bodyfont('Arial');   # set font
$htmll->set_fontsize(8.0);       # set fontsize
$html->set_permissions('none');      

print Dumper $htmll->set_html_content(qq{<html><body>Hello World </body></html>});
$htmll->title();
$htmll->set_header('.', 't', '.');
$htmll->set_footer('D', '.', '/');

print Dumper my $pdf = $htmll->generate_pdf(); # generate document  

 $pdf->to_file("$BASEPATH/macro/$proj/Files/pratik.pdf");
 
 print $htmll->get_html_content();  

######### ######################
ERROR 

$VAR1 = 1; $VAR1 = bless( { 'content' => \undef }, 'HTML::HTMLDoc::PDF' ); Hello World

**Comment by ericschernoff** [comment]
Hello,

That code did work properly for me.  I did need to modify "$html->set_permissions('none');" to add the extra 'l' in $htmll to match the other lines.  I also removed "$BASEPATH/macro/$proj/" since I don't have those variables.  

It is not clear to me what error you are seeing.  Is HTMLDoc producing an empty PDF file without 'Hello World'?  Also, what version of the 'htmldoc' executable do you have?

Thanks,
-Eric

[pratik.pdf](https://github.com/ericschernoff/HTMLDoc/files/4292999/pratik.pdf)

**Comment by Pratiktarade** [comment]
Dear Team ,

Thanks for the  reply
this problem has resolved but still I am facing new  problem I want to set
Custom Text   for header and footer but no such provision provided  even
not mentioned in document how to set custom text . I Request to all please
suggest .. and do needful

Thanks and regard's

Pratik

**Comment by Pratiktarade** [comment]
###
